{
 "title": "MTOGO - Overview",
 "tags": [
  "mtogo",
  "exam"
 ],
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "service", "label": "Service", "query": "gateway,ordering,legacy-menu" }
  ]
 },
 "panels": [
  {
   "title": "Requests/sec (selected service)",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 0, "w": 24, "h": 8 },
   "targets": [
    {
     "expr": "sum(rate(http_requests_received_total{job=\"$service\"}[1m]))"
    }
   ]
  },
  {
   "title": "5xx errors/sec (selected service)",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 8, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "sum(rate(http_requests_received_total{job=\"$service\",code=~\"5..\"}[5m]))"
    }
   ]
  },
  {
   "title": "Latency p95 (selected service)",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 8, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket{job=\"$service\"}[5m])) by (le))"
    }
   ]
  },
  {
   "title": "Ordering: 503 dependency failures/sec",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 16, "w": 24, "h": 8 },
   "targets": [
    {
     "expr": "sum(rate(http_requests_received_total{job=\"ordering\",code=\"503\"}[2m]))"
    }
   ]
  }
 ]
}